basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('basket/', views.view_basket, name='view_basket'),
    path('add/<item_id>/', views.add_items_to_basket,
         name='add_items_to_basket'),
    path('adjust/<item_id>/', views.adjust_basket,
         name='adjust_basket'),
    path('remove/<item_id>/', views.remove_from_basket,
         name='remove_from_basket'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blogpage/', views.HomeBlogView, name='blogpage'),
    path('add_post/', views.UserAddPost, name='add_post'),
    path('<slug>/', views.blogPostDetail, name='blog_post_details'),
    path('edit_post/<slug:slug>/', views.BlogPostEdit, name='edit_post'),
    path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),
]

candy_cave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('sweets/', include('sweets.urls')),
    path('basket/', include('basket.urls')),
    path('profile/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'candy_cave.views.handler404'
handler500 = 'candy_cave.views.handler500'

sweets/urls.py
from django.urls import path
from . import views

app_name = 'sweets'

urlpatterns = [
    path('', views.all_sweets, name='sweets'),
    path('<int:product_id>/', views.individual_sweet, name='sweet_individual'),
    path('amend/', views.user_add_sweets, name='amend_sweets'),
    path('edit/<int:product_id>/', views.edit_sweet, name='edit_sweet'),
    path('delete/<int:product_id>/', views.delete_sweet, name='delete_sweet'),
]

sweets/models.py
from django.db import models


class Category(models.Model):
    """
    To physically see the fixture types see fixtures Ollie!
    Meta class to overwrite django auto 'Categorys'
    """
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=250)
    friendly_name = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Sweet(models.Model):
    """
    Model for the Sweets on the site added with fixtures
    """
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    name = models.CharField(max_length=250)
    detail = models.TextField()
    measurement_of_sweet = models.BooleanField(default=False,
                                               null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=1,
                                 null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def info(self):
        return self.detail

    def __str__(self):
        return self.name

    def get_display_price(self):
        return self.price * 100

    def users_price(self):
        return self.measurement_of_sweet * self.price

sweets/forms.py
from django import forms
from .models import Sweet, Category


class SweetForm(forms.ModelForm):

    class Meta:
        model = Sweet
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(e.id, e.get_friendly_name()) for e in categories]

        self.fields['category'].choiuces = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black round-0'

sweets/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower

from sweets.forms import SweetForm
from .models import Sweet, Category
from .forms import SweetForm


def all_sweets(request):
    """
    View that the main sweet page
    """
    sweets = Sweet.objects.all()
    query = None
    sweet_type = None
    sort = None
    direction = None
    sort_type = None

    if request.GET:
        # Not creditable to myself (Code Institute LMS for below lines 19-30)
        if 'sort' in request.GET:
            sort_type = request.GET['sort']
            sort = sort_type
            if sort_type == 'name':
                sort_type == 'lowername'
                sweets = sweets.annotate(lower_name=Lower('name'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sort_type = f'-{sort_type}'
            sweets = sweets.order_by(sort_type)

        if 'category' in request.GET:
            sweet_type = request.GET['category']
            sweets = sweets.filter(category__name=sweet_type)
            sweet_type = Category.objects.filter(name__in=sweet_type)

        if 'search' in request.GET:
            query = request.GET['search']
            if not query:
                messages.error(request, "Please enter something to search")
                return redirect(reverse('sweets:sweets'))

            queries = Q(name__icontains=query) | Q(detail__icontains=query)
            sweets = sweets.filter(queries)

    sorting_method = f'{sort}_{direction}'

    context = {
        'sweets': sweets,
        'search_term': query,
        'sweet_type': sweet_type,
        'sorting_method': sorting_method,
    }
    return render(request, 'sweets/sweets.html', context)


def individual_sweet(request, product_id):
    """
    Shows the individual sweet
    """
    sweet = get_object_or_404(Sweet, pk=product_id)

    context = {
        'sweet': sweet,
    }
    return render(request, 'sweets/individual_sweet.html', context)


@login_required
def user_add_sweets(request):
    if not request.user.is_superuser:
        messages.error(request, 'Sorry not a Superuser!')
        return redirect(reverse('sweets:sweets'))
    if request.method == 'POST':
        form = SweetForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added sweet to shop')
            return redirect(reverse('sweets:amend_sweets'))
        else:
            messages.error(request, 'failed to add product!')
    else:
        form = SweetForm()

    template = 'sweets/amend_sweets.html'
    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def edit_sweet(request, product_id):
    """
    Edit existing product
    """
    sweet = get_object_or_404(Sweet, pk=product_id)
    if not request.user.is_superuser:
        messages.error(request, 'Sorry not a Superuser!')
        return redirect(reverse('sweets:sweets'))
    if request.method == 'POST':
        form = SweetForm(request.POST, request.FILES, instance=sweet)
        if form.is_valid():
            form.save()
            messages.success(request, "Great changes have been made")
            return redirect(reverse('sweets:sweet_individual',
                                    args=[sweet.id]))
        else:
            messages.error(request, 'Please check the form again!')
    else:
        form = SweetForm(instance=sweet)
        messages.info(request, f'Your about to edit {sweet.name}')

    template = 'sweets/edit_sweets.html'
    context = {
        'form': form,
        'sweet': sweet
    }
    return render(request, template, context)


@login_required
def delete_sweet(request, product_id):
    """
    Edit existing product
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry not a Superuser!')
        return redirect(reverse('sweets:sweets'))
    sweet = get_object_or_404(Sweet, pk=product_id)
    sweet.delete()
    messages.success(request, 'Thats that in the bin!')
    return redirect(reverse('sweets:sweets'))

sweets/templates/sweets/amend_sweets.html
{% extends "base.html" %}
{% load static %}


{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Amend Products</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'sweets:amend_sweets' %}" class="form mb-1" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn" href="{% url 'sweets:sweets' %}">Cancel</a>
                        <button class="btn" type="submit">Add a Sweet</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

sweets/templates/sweets/edit_sweets.html
{% extends "base.html" %}
{% load static %}


{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Edit Products</h2>
                <hr>
            </div>
        </div>

        <div class="row bg-profile justify-content-center">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'sweets:edit_sweet' sweet.id %}" class="form mb-1" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn" href="{% url 'sweets:sweets' %}">Cancel</a>
                        <button class="btn" type="submit">Update a Sweet</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

sweets/templates/sweets/individual_sweet.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="main-product-container">
    {% if sweet.category %}
        <a class="text-muted" href="{% url 'sweets:sweets' %}?category={{ sweet.category.name }}">
            <i class="fas fa-tag mr-1"></i>{{ sweet.category.friendly_name }}
        </a>
    {% endif %}
    {% if sweet.image %}
        <img class="sweet-image-individual" src="{{ sweet.image.url }}" alt="{{ sweet.name }}">
    {% endif %}
    <h5 class="card-text-name">{{ sweet.name }}</h5>
    <p class="card-text">{{ sweet.info }}</p>
    
    {% if sweet.measurement_of_sweet %}
        <p class="card-text">£{{ sweet_total_price }}</p>
    {% else %}
        <p class="card-text">£{{ sweet.price }}</p>
    {% endif %}
    
    {% if sweet.rating %}
        <small class="card-text-rating"><i class="fas fa-star mr-1"></i>{{sweet.rating }} / 5</small>
    {% else %}
        <small class="card-text-rating">No Rating</small>
    {% endif %}
    <form class="form" action="{% url 'basket:add_items_to_basket' sweet.id %}" method="POST">
        {% csrf_token %}
        <div class="form-row mb-4">
            {% with sweet.measurement_of_sweet as m %}
            {% if m %}
                <div class="col-11">
                    <p>Measurement of SUGARNESS</p>
                    <select class="form-control rounded-0 w-50" name="sweet_measurement" id="id_sweet_measurement">
                        <option value="100">100g</option>
                        <option value="150">150g</option>
                        <option value="200">200g</option>
                        <option value="250">250g</option>
                    </select>
                </div>
            {% endif %}
            <div class="col-12">
                <p class="mt-3"><strong>Quantity:</strong></p>
                <div class="form-group w-50">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <button class="decrement-qty btn btn-black rounded-0"
                                data-item_id="{{ sweet.id }}" id="decrement-qty_{{ sweet.id }}">
                                <span class="basket-but">
                                    <i class="fas fa-minus"></i>
                                </span>
                            </button>
                        </div>
                        <input class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="20" data-item_id="{{ sweet.id }}" id="id_qty_{{ sweet.id }}">
                        <div class="input-group-append">
                            <button class="increment-qty btn btn-black rounded-0"
                                data-item_id="{{ sweet.id }}" id="increment-qty_{{ sweet.id }}">
                                <span class="basket-but">
                                    <i class="fas fa-plus"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-center">
                <a href="{% url 'sweets:sweets' %}" class="btn btn-outline-black rounded-0 mt-5">
                    <span class="icon">
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <span class="text-uppercase bottom-tags">Keep Shopping</span>
                </a>
                <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5 bottom-tags" value="Add to Basket">
            </div>
            <input type="hidden" name="redirect_url" value="{{ request.path }}">
            {% endwith %}
        </div>
    </form>
    {% if request.user.is_superuser %}
        <div class="m-4">
            <small>
                <a class="btn-lg btn-success" href="{% url 'sweets:edit_sweet' sweet.id %}">Edit</a>
                <a class="btn-lg btn-danger" href="{% url 'sweets:delete_sweet' sweet.id %}">Delete</a>
            </small>
        </div>
    {% endif %}
</div>
<script type="text/javascript">

    // Disable +/- buttons outside 1-99 range
    function handleEnableDisable(itemId) {
        var currentValue = parseInt($(`#id_qty_${itemId}`).val());
        var minusDisabled = currentValue < 2;
        var plusDisabled = currentValue > 19;
        $(`#decrement-qty_${itemId}`).prop('disabled', minusDisabled);
        $(`#increment-qty_${itemId}`).prop('disabled', plusDisabled);
    }

    // Ensure proper enabling/disabling of all inputs on page load
    var allQtyInputs = $('.qty_input');
    for(var i = 0; i < allQtyInputs.length; i++){
        var itemId = $(allQtyInputs[i]).data('item_id');
        handleEnableDisable(itemId);
    }

    // Check enable/disable every time the input is changed
    $('.qty_input').change(function() {
        var itemId = $(this).data('item_id');
        handleEnableDisable(itemId);
    });

    // Increment quantity
    $('.increment-qty').click(function(e) {
       e.preventDefault();
       var closestInput = $(this).closest('.input-group').find('.qty_input')[0];
       var currentValue = parseInt($(closestInput).val());
       $(closestInput).val(currentValue + 1);
       var itemId = $(this).data('item_id');
       handleEnableDisable(itemId);
    });

    // Decrement quantity
    $('.decrement-qty').click(function(e) {
       e.preventDefault();
       var closestInput = $(this).closest('.input-group').find('.qty_input')[0];
       var currentValue = parseInt($(closestInput).val());
       $(closestInput).val(currentValue - 1);
       var itemId = $(this).data('item_id');
       handleEnableDisable(itemId);
    });
</script>
{% endblock %}

sweets/templates/sweets/sweets.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center mt-1 mb-2 sweet container">
    <div class="sort-select-wrapper">
        <select id="sweet-filter"
            class="custom-select custom-select-sm rounded-0 border border-{% if sorting_method != 'None_None' %}info{% else %}black{% endif %} sort-bar">
            <option value="reset" {% if sorting_method == 'None_None' %}selected{% endif %}>Sort by...</option>
            <option value="price_asc" {% if sorting_method == 'price_asc' %}selected{% endif %}>Price (low to high)
            </option>
            <option value="price_desc" {% if sorting_method == 'price_desc' %}selected{% endif %}>Price (high to low)
            </option>
            <option value="rating_asc" {% if sorting_method == 'rating_asc' %}selected{% endif %}>Rating (low to high)
            </option>
            <option value="rating_desc" {% if sorting_method == 'rating_desc' %}selected{% endif %}>Rating (high to low)
            </option>
            <option value="name_asc" {% if sorting_method == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
            <option value="name_desc" {% if sorting_method == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
        </select>
        <p class="text-muted mt-3 text-center text-md-left">
            {% if search_term or sweet_type or sorting_method != 'None_None' %}
            <span class="small current-fields"><a class="current-fields" href="{% url 'sweets:sweets' %}">Candy Home</a>
                | </span>
            {% endif %}
            {{ sweets|length }} sweets{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
    </div>
</div>
<div class="row m-0 d-flex justify-content-center">
    {% for sweet in sweets %}
    <div class="mb-4">
        <div class="card col-xl-2 text-center">
            {% if sweet.image %}
            <a href="{% url 'sweets:sweet_individual' sweet.id %}">
                <img class="card-img-top" src="{{ sweet.image.url }}" alt="{{ sweet.name }}">
            </a>
            {% endif %}
            <a href="{% url 'sweets:sweet_individual' sweet.id %}">
            <div class="card-body ">
                <h5 class="card-text-name">{{ sweet.name }}</h5>
                <p class="card-text">{{ sweet.info|truncatechars:40 }}</p>
                {% if sweet.measurement_of_sweet %}
                <p class="card-text">£{{ sweet.get_display_price }} per 100 grams</p>
                {% else %}
                <p class="card-text">£{{ sweet.price }} per packet</p>
                {% endif %}
                {% if sweet.rating %}
                <small class="card-text-rating"><i class="fas fa-star mr-1"></i>{{sweet.rating }} / 5</small>
                {% else %}
                <small class="card-text-rating">No Rating</small>
                {% endif %}
            </div>
            </a>
            {% if sweet.category %}
            <a class="text-muted" href="{% url 'sweets:sweets' %}?category={{ sweet.category.name }}">
                <i class="fas fa-tag mr-1"></i>{{ sweet.category.friendly_name }}
            </a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#sweet-filter').change(function () {
        var filterValue = $(this);
        var currentUrl = new URL(window.location);

        var userChoice = filterValue.val();
        if (userChoice != "reset") {
            var userFilterChoice = userChoice.split("_")[0]
            var direction = userChoice.split("_")[1]
            currentUrl.searchParams.set("sort", userFilterChoice);
            currentUrl.searchParams.set("direction", direction);
            window.location.replace(currentUrl);
        } else {
            currentUrl.searchParams.delete("sort");
            currentUrl.searchParams.delete("direction");

            window.location.replace(currentUrl);

        }
    })
</script>
{% endblock %}