basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('basket/', views.view_basket, name='view_basket'),
    path('add/<item_id>/', views.add_items_to_basket,
         name='add_items_to_basket'),
    path('adjust/<item_id>/', views.adjust_basket,
         name='adjust_basket'),
    path('remove/<item_id>/', views.remove_from_basket,
         name='remove_from_basket'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blogpage/', views.HomeBlogView, name='blogpage'),
    path('add_post/', views.UserAddPost, name='add_post'),
    path('<slug>/', views.blogPostDetail, name='blog_post_details'),
    path('edit_post/<slug:slug>/', views.BlogPostEdit, name='edit_post'),
    path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),
]

candy_cave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('sweets/', include('sweets.urls')),
    path('basket/', include('basket.urls')),
    path('profile/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'candy_cave.views.handler404'
handler500 = 'candy_cave.views.handler500'

checkout/urls.py
from django.urls import path
from . import views
from .webhooks import webhook

app_name = 'checkout'

urlpatterns = [
    path('', views.checkout, name='checkout'),
    path('checkout_success/<order_number>', views.checkout_success,
         name='checkout_success'),
    path('cache_checkout_data/', views.cache_checkout_data,
         name='cache_checkout_data'),
    path('wh/', webhook, name='webhook'),

]

sweets/urls.py
from django.urls import path
from . import views

app_name = 'sweets'

urlpatterns = [
    path('', views.all_sweets, name='sweets'),
    path('<int:product_id>/', views.individual_sweet, name='sweet_individual'),
    path('amend/', views.user_add_sweets, name='amend_sweets'),
    path('edit/<int:product_id>/', views.edit_sweet, name='edit_sweet'),
    path('delete/<int:product_id>/', views.delete_sweet, name='delete_sweet'),
]

basket/models.py
from django.db import models

# Create your models here.

basket/views.py
from django.shortcuts import (
        render,
        redirect,
        reverse,
        HttpResponse,
        get_object_or_404
)

from django.contrib import messages
from sweets.models import Sweet


def view_basket(request):
    """
    Shows the basket and whats in it
    """
    return render(request, 'basket/basket.html')


def add_items_to_basket(request, item_id):
    """
    Adds a users item to there basket
    """
    sweet = get_object_or_404(Sweet, pk=item_id)
    quantity = int(request.POST.get('quantity'))
    redirect_url = request.POST.get('redirect_url')
    basket = request.session.get('basket', {})
    size = None
    if 'sweet_measurement' in request.POST:
        size = request.POST['sweet_measurement']

    if size:
        if item_id in list(basket.keys()):
            if size in basket[item_id]['items_by_size'].keys():
                basket[item_id]['items_by_size'][size] += quantity
                messages.success(
                    request,
                    f'Updated size {size.upper()}{sweet.name} \
                        quantity to {basket[item_id]["items_by_size"][size]}')
            else:
                basket[item_id]['items_by_size'][size] = quantity
                messages.success(
                    request, f'Added size{size.upper()} \
                        {sweet.name} to your basket')
        else:
            basket[item_id] = {'items_by_size': {size: quantity}}
            messages.success(request, f'Added size{size.upper()} \
                {sweet.name} to your basket')
    else:
        if item_id in list(basket.keys()):
            basket[item_id] += quantity
            messages.success(request, f'Updated{sweet.name} \
                quantity to {basket[item_id]}')
        else:
            basket[item_id] = quantity
            messages.success(request, f'Added{sweet.name} \
                to your basket')

    request.session['basket'] = basket
    return redirect(redirect_url)


def adjust_basket(request, item_id):
    """Adjust the quantity of the specified sweet to the specified amount"""
    sweet = get_object_or_404(Sweet, pk=item_id)
    quantity = int(request.POST.get('quantity'))
    size = None
    if 'sweet_measurement' in request.POST:
        size = request.POST['sweet_measurement']
    basket = request.session.get('basket', {})
    if size:
        if quantity > 0:
            basket[item_id]['items_by_size'][size] = quantity
            messages.success(request, f'Updated size \
                {size.upper()}{sweet.name} quantity \
                    to{basket[item_id]["items_by_size"][size]}')
        else:
            del basket[item_id]['items_by_size'][size]
            if not basket[item_id]['items_by_size']:
                basket.pop(item_id)
                messages.success(request, f'Removed size{size.upper()} \
                    {sweet.name} from your bag')
    else:
        if quantity > 0:
            basket[item_id] = quantity
            messages.success(request, f'Updated{sweet.name} \
                quantity to {basket[item_id]}')
        else:
            basket.pop(item_id)
            messages.success(request, f'Removed {sweet.name} \
                from your bag')

    request.session['basket'] = basket
    return redirect(reverse('basket:view_basket'))


def remove_from_basket(request, item_id):
    """Remove the item from the shopping bag"""

    try:
        sweet = get_object_or_404(Sweet, pk=item_id)
        size = None
        if 'sweet_measurement' in request.POST:
            size = request.POST['sweet_measurement']
        basket = request.session.get('basket', {})

        if size:
            del basket[item_id]['items_by_size'][size]
            if not basket[item_id]['items_by_size']:
                basket.pop(item_id)
                messages.success(request, f'Removed size \
                    {size.upper()}{sweet.name} from your bag')
        else:
            basket.pop(item_id)
            messages.success(request, f'Removed {sweet.name} from your bag')

        request.session['basket'] = basket
        return HttpResponse(status=200)

    except Exception as e:
        messages.error(request, f'Error removing item: {e}')
        return HttpResponse(status=500)

basket/templates/basket/basket.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container-for-footer container-fluid">
        <div class="container mb-2">
            <div class="row">
                <div class="col">
                    <h2 class="basket-header text-center">Welcome to your Goody Bag</h2>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    {% if basket_selection %}
                        <br>
                        <br>
                        <div class="table-responsive rounded table-checkout">
                            <table class="table table-sm table">
                                <thead class="basket-table">
                                    <tr>
                                        <th class="table-decription text-danger">Sweet</th>
                                        <th class="table-decription text-danger">Description</th>
                                        <th class="table-decription text-danger"></th>
                                        <th class="table-decription text-danger">Quantity</th>
                                        <th class="table-decription text-danger">Price</th>
                                    </tr>
                                </thead>
                                {% for item in basket_selection %}
                                    <tr class="basket-table">
                                        <td class="p-3 w-25">
                                            <img class="img-fluid rounded" alt="product-image" src="{{ item.sweet.image.url }}">
                                        </td>
                                        <td class="py-3">
                                                <p class="my-0"><strong>{{item.sweet.name}}</strong></p>
                                        </td>
                                        <td class="py-3 w-25">
                                            <p class="my-0">{{ item.sweet.detail|truncatechars:25 }}</p>
                                        </td>
                                        <td class="py-3 w-25">
                                            <p class="my-0">{{ item.quantity }}</p>
                                            <td class="py-3">
                                                <form class="form update-form" method="POST" action="{% url 'basket:adjust_basket' item.item_id %}">
                                                    {% csrf_token %}
                                                    <div class="form-group">
                                                        <div class="input-group">
                                                            <div class="input-group-prepend">
                                                                <button class="decrement-qty btn btn-sm btn-black rounded-0" 
                                                                    data-item_id="{{ item.item_id }}" id="decrement-qty_{{ item.item_id }}">
                                                                    <span>
                                                                        <i class="fas fa-minus fa-sm"></i>
                                                                    </span>
                                                                </button>
                                                            </div>
                                                            <input class="form-control form-control-sm qty_input" type="number"
                                                                name="quantity" value="{{ item.quantity }}" min="1" max="99"
                                                                data-item_id="{{ item.item_id }}"
                                                                id="id_qty_{{ item.item_id }}">
                                                            <div class="input-group-append">
                                                                <button class="increment-qty btn btn-sm btn-black rounded-0"
                                                                    data-item_id="{{ item.item_id }}" id="increment-qty_{{ item.item_id }}">
                                                                    <span>
                                                                        <i class="fas fa-plus fa-sm"></i>
                                                                    </span>
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                                <a class="update-link text-info"><small>Update</small></a>
                                                <a class="remove-item text-danger float-right" id="remove_{{ item.item_id }}" data-sweet_measurement="{{ item.size }}"><small>Remove</small></a>
                                        </td>
                                        {% if item.sweet.measurement_of_sweet %}
                                            <td class="py-3 bottom-checkout">
                                                <p>£{{ item.sweet_total_price }}</p>
                                            </td>
                                        {% else %}
                                            <td class="py-3 bottom-checkout">
                                                <p>£{{ item.sweet.price }}</p>
                                            </td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <td colspan="5" class="pt-5 text-right basket-table bottom-checkout">
                                            <h6 class="bottom-checkout"><strong>Bag Total: ${{ basket_sum|floatformat:2 }}</strong></h6>
                                            <h6 class="bottom-checkout">Postage: ${{ post|floatformat:2 }}</h6>
                                            <h4 class="mt-4 bottom-checkout"><strong>Grand Total: ${{ grand_total|floatformat:2 }}</strong></h4>
                                            {% if free_postage_mark > 0 %}
                                                <p class="mb-1 text-danger bottom-checkout">
                                                    You could get free postage by spending just <strong>${{ free_postage_mark }}</strong> more!
                                                </p>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="5" class="text-right">
                                            <a href="{% url 'sweets:sweets' %}" class="btn btn-outline-black rounded-0 btn-lg">
                                                <span class="icon">
                                                    <i class="fas fa-chevron-left"></i>
                                                </span>
                                                <span class="text-uppercase bottom-checkout">Keep Shopping</span>
                                            </a>
                                            <a href="{% url 'checkout:checkout' %}" class="btn btn-black rounded-0 btn-lg">
                                                <span class="text-uppercase bottom-checkout">Secure Checkout</span>
                                                <span class="icon">
                                                    <i class="fas fa-lock"></i>
                                                </span>
                                            </a>
                                        </td>
                                    </tr>
                            </table>
                        </div>
                    {% else %}
                        <p class="basket-empty">Hmmmm Theres Nothing Sweet in here!!! Get Back shopping!
                        <a href="{% url 'sweets:sweets' %}" class="btn shop-btn btn-lg">SHOP NOW</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
<script type="text/javascript">

    // Disable +/- buttons outside 1-99 range
    function handleEnableDisable(itemId) {
        var currentValue = parseInt($(`#id_qty_${itemId}`).val());
        var minusDisabled = currentValue < 2;
        var plusDisabled = currentValue > 19;
        $(`#decrement-qty_${itemId}`).prop('disabled', minusDisabled);
        $(`#increment-qty_${itemId}`).prop('disabled', plusDisabled);
    }

    // Ensure proper enabling/disabling of all inputs on page load
    var allQtyInputs = $('.qty_input');
    for(var i = 0; i < allQtyInputs.length; i++){
        var itemId = $(allQtyInputs[i]).data('item_id');
        handleEnableDisable(itemId);
    }

    // Check enable/disable every time the input is changed
    $('.qty_input').change(function() {
        var itemId = $(this).data('item_id');
        handleEnableDisable(itemId);
    });

    // Increment quantity
    $('.increment-qty').click(function(e) {
        e.preventDefault();
        var closestInput = $(this).closest('.input-group').find('.qty_input')[0];
        var currentValue = parseInt($(closestInput).val());
        $(closestInput).val(currentValue + 1);
        var itemId = $(this).data('item_id');
        handleEnableDisable(itemId);
    });

    // Decrement quantity
    $('.decrement-qty').click(function(e) {
        e.preventDefault();
        var closestInput = $(this).closest('.input-group').find('.qty_input')[0];
        var currentValue = parseInt($(closestInput).val());
        $(closestInput).val(currentValue - 1);
        var itemId = $(this).data('item_id');
        handleEnableDisable(itemId);
    });

    // Updates the form after increment/decrement
    $('.update-link').click(function(e) {
        var form = $(this).prev('.update-form');
        form.submit();
    })

    
    // Remove item and reload on click
    $('.remove-item').click(function(e) {
        var csrfToken = "{{ csrf_token }}";
        var itemId = $(this).attr('id').split('remove_')[1];
        var size = $(this).data('size/');
        var url = `/basket/remove/${itemId}/`;
        var data = {'csrfmiddlewaretoken': csrfToken, 'sweet_measurement': size};

        $.post(url, data)
         .done(function() {
             location.reload();
         });
    })
</script>
{% endblock %}