blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blogpage/', views.HomeBlogView, name='blogpage'),
    path('add_post/', views.UserAddPost, name='add_post'),
    path('<slug>/', views.blogPostDetail, name='blog_post_details'),
    path('edit_post/<slug:slug>/', views.BlogPostEdit, name='edit_post'),
    path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),
]

candy_cave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('sweets/', include('sweets.urls')),
    path('basket/', include('basket.urls')),
    path('profile/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'candy_cave.views.handler404'
handler500 = 'candy_cave.views.handler500'

sweets/urls.py
from django.urls import path
from . import views

app_name = 'sweets'

urlpatterns = [
    path('', views.all_sweets, name='sweets'),
    path('<int:product_id>/', views.individual_sweet, name='sweet_individual'),
    path('amend/', views.user_add_sweets, name='amend_sweets'),
    path('edit/<int:product_id>/', views.edit_sweet, name='edit_sweet'),
    path('delete/<int:product_id>/', views.delete_sweet, name='delete_sweet'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Posts(models.Model):
    """
    Users Posts
    """
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, null=False, blank=False,
                               on_delete=models.SET_DEFAULT, default=1)
    body = models.TextField(max_length=10000)
    slug = models.SlugField(max_length=128, unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug:
            if slugify(self.title) != self.slug:
                self.slug = slugify(self.title)
        else:
            self.slug = slugify(self.title)
        super(Posts, self).save(*args, **kwargs)

blog/forms.py
from django import forms
from .models import Posts


class BlogForm(forms.ModelForm):
    class Meta:
        model = Posts
        exclude = ('author', 'slug',)

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.contrib.auth.decorators import login_required
from .models import Posts
from .forms import BlogForm
from django.contrib import messages
# Create your views here.


def HomeBlogView(request):
    blog_posts = Posts.objects.all()
    context = {
        'blog_posts': blog_posts
    }
    return render(request, 'blog/blogpage.html', context)


def blogPostDetail(request, slug):
    '''
    View to return individual blog post
    '''
    post = get_object_or_404(Posts, slug=slug)
    context = {
        'post': post,
    }
    return render(request, 'blog/blog_post_details.html', context)


@login_required
def UserAddPost(request):
    """
    A view to give users ability to add a post
    """
    form = BlogForm()
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            new_post_blog_post = form.save(commit=False)
            new_post_blog_post.author = request.user
            new_post_blog_post.save()
            messages.success(request, 'Wicked your post is LIVE!')
            return redirect(reverse('blog:blogpage'))
        else:
            messages.error(request, 'failed to add post!')
    template = 'blog/add_post.html'
    return render(request, template, context)


@login_required
def BlogPostEdit(request, slug):
    '''
    View to display prefilled form to edit a blog post
    and to handle form processing
    '''
    post = get_object_or_404(Posts, slug=slug)
    if not request.user == post.author:
        messages.error(request, 'This is not your post')
        return redirect('blog:blogpage')
    form = BlogForm(instance=post)
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES or None, instance=post)
        if form.is_valid():
            changed_form = form.save(commit=False)
            changed_form.author = request.user
            changed_form.save()
            messages.success(request, 'Successfully edited your blog post')
            return redirect('blog:blogpage')
        else:
            messages.error(request, 'Failed to update blog post, \
                please double check the form.')

    context = {
        'form': form,
        'post': post
    }

    return render(request, 'blog/add_post.html', context)


@login_required
def deletePost(request, slug):
    '''
    View to handle the deletion of a blog post
    '''
    post = get_object_or_404(Posts, slug=slug)
    if not request.user == post.author:
        messages.error(request, 'This is not your post')
        return redirect('blog:blogpage')
    post.delete()
    messages.success(request, 'The post has been deleted.')
    return redirect('blog:blogpage')

blog/templates/blog/add_post.html
{% extends "base.html" %}
{% load static %}


{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                {% if post %}
                    <h2>Edit Blog Post</h2>
                {% else %}
                    <h2>Add Blog Post</h2>
                {% endif %}
                <form method="POST" action="{% if post %}{% url 'blog:edit_post' post.slug %}{% else %}{% url 'blog:add_post' %}{% endif %}" class="form mb-1" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn" href="{% url 'sweets:sweets' %}">Cancel</a>
                        <button type="submit" class="btn btn-primary mt-2">{% if post %}Save Changes{% else %}Add Blog Post{% endif %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_post_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="row m-0 d-flex justify-content-center">
        <div class="card col-xl-2 text-center">
            <div class="card-body">
                <h5 class="card-text-name card-blog-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.body|truncatechars:100 }}</p>
                <p class="card-blog-title">{{ post.author }}</p>
            </div>
        </div>
        {% if user == post.author %}
            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'blog:edit_post' post.slug %}">Update</a>
            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'blog:delete_post' post.slug %}">Delete</a>
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/blogpage.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid container-for-footer">
    <div class="row">
        <div class="col bg-black text-white">
            <div class="d-flex justify-content-center post">
                <p class="blog-hero mr-2">Welcome to the CandyForum Where all the sugary thoughts expierences are shared!!! <a class="blog-hero-add" href="{% url 'blog:add_post' %}">Add A Post Here!</a></p>
                
                <div>
                </div>
            </div>
            <div class="row d-flex justify-content-center w-100">
                {% for post in blog_posts %}
                    <a  class="m-4" href="{% url 'blog:blog_post_details' post.slug %}">
                        <div class="m-4 card col-xl-2 text-center">
                            <div class="card-body">
                                <h5 class="card-text-name-blog">{{ post.title }}</h5>
                                <p class="card-text">{{ post.body|truncatechars:100 }}</p>
                                <p class="card-text-author">By- {{ post.author }}</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}
    