basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('basket/', views.view_basket, name='view_basket'),
    path('add/<item_id>/', views.add_items_to_basket,
         name='add_items_to_basket'),
    path('adjust/<item_id>/', views.adjust_basket,
         name='adjust_basket'),
    path('remove/<item_id>/', views.remove_from_basket,
         name='remove_from_basket'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('blogpage/', views.HomeBlogView, name='blogpage'),
    path('add_post/', views.UserAddPost, name='add_post'),
    path('<slug>/', views.blogPostDetail, name='blog_post_details'),
    path('edit_post/<slug:slug>/', views.BlogPostEdit, name='edit_post'),
    path('delete_post/<slug:slug>/', views.deletePost, name='delete_post'),
]

candy_cave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('sweets/', include('sweets.urls')),
    path('basket/', include('basket.urls')),
    path('profile/', include('profiles.urls')),
    path('checkout/', include('checkout.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'candy_cave.views.handler404'
handler500 = 'candy_cave.views.handler500'

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact-us'),
    path('contact-form/', views.contactForm, name='contact-form'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('order_history/<order_number>', views.order_history,
         name='order_history'),
]

sweets/urls.py
from django.urls import path
from . import views

app_name = 'sweets'

urlpatterns = [
    path('', views.all_sweets, name='sweets'),
    path('<int:product_id>/', views.individual_sweet, name='sweet_individual'),
    path('amend/', views.user_add_sweets, name='amend_sweets'),
    path('edit/<int:product_id>/', views.edit_sweet, name='edit_sweet'),
    path('delete/<int:product_id>/', views.delete_sweet, name='delete_sweet'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  {% block meta %}
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Sweets Shop Candy Cave England Jars Gifts Sweet Sugar Confectionary">
  <meta name="keywords" content="Sweets, Shop, Candy Cave, England, Jars, Gifts, Sweet, Sugar, Confectionary">
  {% endblock %}

  {% block extra_meta %}
  {% endblock %}

  {% block corecss %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Lato:wght@300&display=swap" rel="stylesheet">
  <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7_dtp.css" rel="stylesheet" type="text/css">
  <link rel="apple-touch-icon" sizes="180x180" href="s3://candycave/media/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32"
    href="https://candycave.s3.eu-west-2.amazonaws.com/media/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16"
    href="https://candycave.s3.eu-west-2.amazonaws.com/media/favicon-16x16.png">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% endblock %}

  {% block extra_css %}
  {% endblock %}

  {% block corejs %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/">
  </script>
  {% endblock %}

  {% block extra_js %}
  {% endblock %}

  <title>Candy Cave {% block extra_title %}{% endblock %}</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg mb-4 navbar-back">
      <a class="navbar-brand nav-theme mr-4" href="{% url 'home:home' %}">CandyCave</a>
      <button class="navbar-toggler nav-logo" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">Menu</span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link active nav-theme" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item nav-theme">
            <a class="nav-link nav-theme" href="{% url 'home:about' %}">About</a>
          </li>
          <li class="nav-item nav-theme">
            <a class="nav-link nav-theme" href="{% url 'blog:blogpage' %}">Blog</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle nav-theme" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if request.user.is_authenticated %}
              {% if request.user.is_superuser %}
                <a href="{% url 'sweets:amend_sweets' %}" class="dropdown-item nav-theme-dropdown">Sweet
                  Management</a>
              {% endif %}
                <a href="{% url 'profile:profile' %}" class="dropdown-item nav-theme-dropdown">My Profile</a>
                <a href="{% url 'account_logout' %}" class="dropdown-item nav-theme-dropdown">Logout</a>
              {% else %}
                <a href="{% url 'account_signup' %}" class="dropdown-item nav-theme-dropdown">Signup</a>
                <a href="{% url 'account_login' %}" class="dropdown-item nav-theme-dropdown">Login</a>
              {% endif %}
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle nav-theme" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Shop
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
              <a class="dropdown-item nav-theme-dropdown" href="{% url 'sweets:sweets' %}">All Sweets!<i
                  class="fa-solid fa-candy"></i></a>
                
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?sort=price&direction=asc">By Price<i
                    class="fa-solid fa-party-horn"></i></a>
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?sort=rating&direction=desc">By Rating<i
                    class="fa-solid fa-party-horn"></i></a>
              <hr class="dropdown-divider">
              <p class="nav-headings">By Sweet Type</p>
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?category=squidgy">Squidgy<i
                    class="fa-solid fa-party-horn"></i></a>
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?category=sour">Sour<i class="fa-solid fa-party-horn"></i></a>
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?category=hard">Boiled/Hard<i
                    class="fa-solid fa-party-horn"></i></a>
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?category=chocolate">Chocolate<i
                    class="fa-solid fa-party-horn"></i></a>
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?category=wrapped">Wrapped<i
                    class="fa-solid fa-party-horn"></i></a>
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?category=long">Long<i class="fa-solid fa-party-horn"></i></a>
              
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?category=new_arrivals">New Arrivals<i
                    class="fa-solid fa-party-horn"></i></a>
              <a class="dropdown-item nav-theme-dropdown"
                  href="{% url 'sweets:sweets' %}?category=the_classics">The Classics<i
                    class="fa-solid fa-party-horn"></i></a>
            </div>
          </li>
        </ul>
        <div><a class="basket" href="{% url 'basket:view_basket' %}"><i
          class="fa-solid fa-basket-shopping basket"></i></a>
        </div>
        <p class="my-0 basket">
        {% if grand_total %}
        ${{ grand_total|floatformat:2 }}
        {% else %}
        $0.00
        {% endif %}
        </p>
          <form method="GET" action="{% url 'sweets:sweets' %}" class="d-flex justify-content-center">
          <input class="form-control me-2 search-bar" type="text" name="search" placeholder="Search FOR GOODIES">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>

  {% if messages %}
  <div class="message-container">
    {% for message in messages %}
    {% with message.level as level %}
    {% if level == 40 %}
    {% include 'includes/toasts/toast_error.html' %}
    {% elif level == 30 %}
    {% include 'includes/toasts/toast_warning.html' %}
    {% elif level == 25 %}
    {% include 'includes/toasts/toast_success.html' %}
    {% else %}
    {% include 'includes/toasts/toast_info.html' %}
    {% endif %}
    {% endwith %}
    {% endfor %}
  </div>
  {% endif %}


  {% block page_header %}
  {% endblock %}

  {% block content %}
  {% endblock %}
  <div class="footer-outer-container">
    <footer>
      <div class="mt-4 container py-5">
        <div class="row py-4 font-footer">
          <div class="col-lg-4 socials col-md-6 mb-4 mb-lg-0">
            <p class="font-italic green-footer">Taking the candy... out of the cave</p>
            <ul class="list-inline mt-4">
              <li class="list-inline-item"><a href="https://www.facebook.com" target="_blank" title="facebook" aria-label="Go to our Facebook page (opens in new tab)" rel="noopener"><i
                    class="fa fa-facebook footer-logos"></i></a></li>
              <li class="list-inline-item"><a href="https://www.instagram.com" target="_blank" title="instagram" aria-label="Go to our Instagram page (opens in new tab)" rel="noopener"><i
                    class="fa fa-instagram footer-logos"></i></a></li>
            </ul>
          </div>
          <div class="col-lg-2 col-md-6 mb-4 mb-lg-0 footer-box">
            <h6 class="text-uppercase font-weight-bold mb-4 green-footer">Shop</h6>
            <ul class="list-unstyled mb-0">
              <li class="mb-2"><a href="{% url 'sweets:sweets' %}" class="my-footer-links">All Sweets</a></li>
              <li class="mb-2"><a href="{% url 'sweets:sweets' %}?sort=price&direction=asc" class="my-footer-links">By
                  Price</a></li>
              <li class="mb-2"><a href="{% url 'sweets:sweets' %}?sort=rating&direction=desc" class="my-footer-links">By
                  Rating</a></li>
            </ul>
          </div>
          <div class="col-lg-2 col-md-6 mb-4 mb-lg-0 footer-box">
            <h6 class="text-uppercase font-weight-bold mb-4 green-footer">Sweety Stores</h6>
            <ul class="list-unstyled mb-0">
              <li class="mb-2"><a href="{% url 'account_login' %}" class="my-footer-links">Login</a></li>
              <li class="mb-2"><a href="{% url 'account_signup' %}" class="my-footer-links">Signup</a></li>
            </ul>
          </div>
          <!-- Begin Mailchimp Signup Form -->
          <div id="mc_embed_signup">
            <form
              action="https://herokuapp.us12.list-manage.com/subscribe/post?u=8b00e9a876ce5a8deef7c5c94&amp;id=7132f3b8ab"
              method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="chimp validate"
              target="_blank" novalidate>
              <div id="mc_embed_signup_scroll">
                <h2 class="green-footer">Subscribe</h2>
                <div class="green-footer indicates-required"><span class="asterisk">*</span> indicates required</div>
                <div class="mc-field-group">
                  <label for="mce-EMAIL" class="footer-form-sub green-footer">Email Address <span
                      class="asterisk">*</span>
                  </label>
                  <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
                </div>
                <div id="mce-responses" class="clear foot">
                  <div class="response" id="mce-error-response" style="display:none"></div>
                  <div class="response" id="mce-success-response" style="display:none"></div>
                </div>
                <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
                    name="b_8b00e9a876ce5a8deef7c5c94_7132f3b8ab" tabindex="-1" value=""></div>
                <div class="optionalParent">
                  <div class="clear foot">
                    <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"
                      class="btn-success btn-lg w-50">
                    <p class="brandingLogo"><a href="http://eepurl.com/h7V_E5"
                        title="Mailchimp - email marketing made easy and fun"><img alt="mail-chimp"
                          src="https://eep.io/mc-cdn-images/template_images/branding_logo_text_dark_dtp.svg"></a></p>
                  </div>
                </div>
              </div>
            </form>
          </div>
          <!--End mc_embed_signup-->
        </div>
      </div>

      <!-- Copyrights -->
      <div class="bg-light py-4">
        <div class="container text-center">
          <a href="https://www.privacypolicygenerator.info/live.php?token=ozARu6M33OX0cRUxqUEyQHYK2yTOK6mt">
            <p class="text-muted mb-0 py-2">© 2022 CandyCave All rights reserved.</p>
          </a>
        </div>
      </div>
    </footer>
  </div>

  {% block postloadjs %}
  <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script>
  <script
    type='text/javascript'>(function ($) { window.fnames = new Array(); window.ftypes = new Array(); fnames[0] = 'EMAIL'; ftypes[0] = 'email'; fnames[1] = 'FNAME'; ftypes[1] = 'text'; fnames[2] = 'LNAME'; ftypes[2] = 'text'; fnames[3] = 'ADDRESS'; ftypes[3] = 'address'; fnames[4] = 'PHONE'; ftypes[4] = 'phone'; fnames[5] = 'BIRTHDAY'; ftypes[5] = 'birthday'; }(jQuery)); var $mcj = jQuery.noConflict(true);</script>
  <script type="text/javascript">
    $('.toast').toast('show');
  </script>
  <script src="https://kit.fontawesome.com/d6c0aae822.js" crossorigin="anonymous"></script>
  {% endblock %}


</body>

</html>